### ISSUE TITLE
Selecting Telescope as First Part When Building a New Vessel Breaks VAB/SPH Editor

### ISSUE THREAD

**Issue by Zondulus** [post-kerbin-mining-corporation/SpaceDust#15]
Summary: Selecting the "PT-EDW1N Spectral Telescope" as the first part when creating a new vessel in the VAB or SPH breaks the editor in a number of ways.

Steps to reproduce:
1. Go to VAB or SPH
2. Create a new vessel
3. Select the Spectral Telescope as the first part

A number of things break (apologies if this is too exhaustive):

- No "object placing" noise occurs when selecting the telescope as the first part, unlike every other part
- You cannot left-click grab the telescope. You can right click it and configure its experiments
- You cannot move, rotate, or re-root the telescope using those editor tools
- When selecting new parts from the part menu, you can't rotate those new parts once added
- Trying to place new parts on the telescope shows new parts as green but doesn't place them when you click
- You cannot make a new craft, save, or change the name or description, but you can load a different craft or leave the VAB, both of which let you edit other crafts like normal
- Reloading the craft with the telescope as the root part works but acts extremely weirdly, with other parts appearing as the root and having the same part attachment problems as before

Note that this bug does not occur when the spectral telescope is not selected as the first part. You are still able to attach the telescope to other craft and can even switch the root part to the telescope without triggering these weird issues.

Log attached. I can also supply the modlist but it isn't too extensive and this bug never occurred before installing Space Dust & is related to Space Dust parts.

[Player.log](https://github.com/ChrisAdderley/SpaceDust/files/5447706/Player.log)

**Comment by ChrisAdderley** [comment]
Resolved in 0.1.1
