### ISSUE TITLE
Attachment point is inside telescope

### ISSUE THREAD

**Issue by linuxgurugamer** [post-kerbin-mining-corporation/SpaceDust#23]
Not sure if this is intentional, but I found that the attachment point for the telescope is inside it, near the bottom.  
This can be awkward to attach to a seperator or decoupler, especially when decoupling

**Comment by ChrisAdderley** [comment]
Yes, intentional. The attach point is at the base of the telescope, see https://www.nasa.gov/sites/default/files/thumbnails/image/hubbleinstruments-graphic.gif.
The intention is to let you build your own control 'bus' for it instead of building a hubble-alike one.
