### ISSUE TITLE
Bizarre bug

### ISSUE THREAD

**Issue by coyotesfrontier** [post-kerbin-mining-corporation/SpaceDust#30]
This is a really odd bug that I've narrowed down to SpaceDust: Every time I load a save, the science is set to 285. Tested in 1.10.1 with no other mods then B9PartSwitch (and both DLCs).

Log File:
https://pastebin.com/wKeq64f4

ConfigSHA:
https://pastebin.com/75A2ywMG

**Comment by ChrisAdderley** [comment]
Resolved some time in the past.
