### ISSUE TITLE
Hydrogen density at Jool

### ISSUE THREAD

**Issue by LouisB3** [post-kerbin-mining-corporation/SpaceDust#36]
I am working to understand the SpaceDust configs better so that I can extend compatibility to planet packs such as GEP. While refamiliarizing myself with ideal gas law, I noticed something in the atmospheric LqdHydrogen config at Jool that seemed out of place:

https://github.com/post-kerbin-mining-corporation/SpaceDust/blob/08959c736835f3f5ec6ab0f4529d4197493a1e56/GameData/SpaceDust/Definitions/LqdHydrogen.cfg#L17-L19

Is this correct? A density of 1.1+ metric ton per cubic meter is much higher than liquid hydrogen (0.07085 t/m^3) or solid hydrogen (0.086 t/m^3), and is possibly in the range of metallic hydrogen (0.6 t/m^3).

Relatedly, am I right in thinking that abundances are given at 1 atm, [per the wiki](https://github.com/post-kerbin-mining-corporation/SpaceDust/wiki/Defining-Distributions#define-bands)? 

```
// Scales abundance to pressure (in atm) 
  densityCurve
  {
      key = 0 0
      key = 1 1
      key = 12 12
  }
```

If so I think the abundance would be more like `0.000167923`.

**Comment by ChrisAdderley** [comment]
I think everything is slightly wrong because I used mean atmosphere densities when grabbing the numbers. Needs to be defined as indicated at 1 atm.
