### ISSUE TITLE
Sift-O-Tron 125 and 250 no longer captureing argon gas.

### ISSUE THREAD

**Issue by General-GG** [post-kerbin-mining-corporation/SpaceDust#56]
For some strange reason the last 3 updates of space dust something broke argon gas capture with the Sift-O-Tron 125 and 250 no idea wot happened but in ver 0.4.4 they was both capturing argon gas just fine :/

Here is a screenshot of the issue occurring and my ksp.log hope this helps.

![Argon1](https://github.com/user-attachments/assets/d985d5a7-d60c-49f8-939e-d64c1755755a)
[KSP_log.zip](https://github.com/user-attachments/files/16811599/KSP_log.zip)

**Comment by ChrisAdderley** [comment]
Has been fixed for a few updates
